[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["NODE_ENV=development pnpm install --frozen-lockfile=false"]

[phases.build]
cmds = ["NODE_ENV=development pnpm run build"]

[start]
cmd = "NODE_ENV=production pnpm run start"
